=pod

=encoding utf8

=head1 Catan Game Notation

This document defines a notation for the game Settlers of Catan, called "Catan Game Notation" (CGN). CGN is represented as JSON and is designed to capture "what happened" for a game of Catan using the base game.

=head2 Log

A log of CGN captures the entirety of a game of Catan from setup to end. The log is an array of objects that contain notation describing what happened. See F<example.json> for an entire game log.

=head2 Tiles

All tiles are numbered (including sea tiles), using the axial (trapezoidal) coordinate system:

             0,-3  1,-3  2,-3   3,-3
         -1,-2  0,-2  1,-2   2,-2   3,-2
     -2,-1  -1,-1  0,-1   1,-1   2,-1   3,-1
  -3,0   -2,0   -1,0    0,0    1,0    2,0    3,0
     -3,1   -2,1   -1,1   0,1    1,1    2,1
        -3,2   -2,2   -1,2  0,2    1,2
           -3,3   -2,3   -1,3  0,3

This is the same map with the sea tiles represented by tildes (incorrect notation but easier to interpret visually):

           ~~~~  ~~~~  ~~~~   ~~~~
        ~~~~ 0,-2   1,-2   2,-2  ~~~~
     ~~~~  -1,-1  0,-1  1,-1  2,-1  ~~~~
  ~~~~  -2,0   -1,0   0,0   1,0   2,0  ~~~~
     ~~~~  -2,1   -1,1   0,1   1,1  ~~~~
        ~~~~  -2,2   -1,2   0,2  ~~~~
           ~~~~   ~~~~   ~~~~  ~~~~

=head2 Tile Types

A tile can be any one of the below

  H   Hills
  D   Desert
  HR  Harbor Generic
  HR_ Harbor Specific: B, G, L, O, W
  M   Mountains
  S   Sea
  F   Fields
  FO  Forest
  P   Pastures

=head2 Resource Number

A tile can have one resource number on it, valid numbers are between 2-6 and 8-12. There is also a limit on the frequency of resource numbers. These are all the available resource numbers for a basic game:

  2,3,3,4,4,5,5,6,6,8,8,9,9,10,10,11,11,12

=head2 Tile Notation

Tile notation is used to define the playing map. Every tile is listed with its coordinates, type and resource number. C<null> represents no resource number. The starter map layout:

  [
    [0,-3,"HR",null],
    [1,-3,"S",null],
    [2,-3,"HRW",null],
    [3,-3,"S",null],
    [3,-2,"HR",null],
    [3,-1,"S",null],
    [3,0,"HRG",null],
    [2,1,"S",null],
    [1,2,"HRB",null],
    [0,3,"S",null],
    [-1,3,"HRL",null],
    [-2,3,"S",null],
    [-3,3,"HR",null],
    [-3,2,"S",null],
    [-3,1,"HR",null],
    [-3,0,"S",null],
    [-2,-1,"HRO",null],
    [-1,-2,"S",null],
    [0,-2,"FO",11],
    [1,-2,"P",12],
    [2,-2,"F",9],
    [2,-1,"P",10],
    [2,0,"F",8],
    [1,1,"M",3],
    [0,2,"FO",6],
    [-1,2,"F",2],
    [-2,2,"M",5],
    [-2,1,"H",8],
    [-2,0,"D",null],
    [-1,-1,"H",4],
    [0,-1,"M",6],
    [1,-1,"H",5],
    [1,0,"FO",4],
    [0,1,"P",9],
    [-1,1,"P",10],
    [-1,0,"FO",3],
    [0,0,"F",11]
  ]

=head2 Intersections

Intersections represent a point between 3 tile locations in a clockwise order. Intersections are represented as an array of 3 tile locations. E.g. the six intersections of the center tile on the starter map layout:

                 [[0,-1],[0,0],[-1,0]]
                         /   \
  [[0,-1],[0,0],[-1,0]] /     \  [[1,-1],[1,0],[0,0]]
                       |  0,0  |
                       |       |
  [[0,0],[-1,1],[-1,0]] \     /  [[1,0],[0,1],[0,0]]
                         \   /
                 [[0,1],[-1,1],[0,0]]


=head2 Paths

Paths are lines between contiguous intersections and are represented as an array of intersections. Each path must have at least two intersections:

  [ [[0,0],[-1,1],[-1,0]], [[0,1],[-1,1],[0,0]] ]

=head2 Resources

There are 5 types of resources:

  Code  Type
  ------------
  B     Brick
  G     Grain
  L     Lumber
  O     Ore
  W     Wool

=head2 Resources notation

Resources notation records which resources and in what quantity are being traded by players with the bank or with each other.

It uses the resource code as the key and the value as the quantity. Both quantities gained and lost are listed. So a trade between player 1 and
player 2 for 2 lumber for a wool looks like:

  {
    "1":{"L":-2,"W":1},
    "2":{"L":2,"W":-1 }
  }

The implication of this notation is that all resources must balance. For trades with the bank, C<bank> represents the bank:

  {
    "1":{"G":-4,"B":1},
    "bank":{"G":4,"B":-1}
  }

Resource notation isn't just for trades. It's used for gains from resource production, stealing resources with the robber and conceding resources back to the
bank.

=head2 Assets

Players may accumulate these throughout the game. There are four normal and two
special types:

  Code  Name              How to get it
  ---------------------------------------------------------
  DC    Development card  Build development card event (BD)
  S     Settlement        Build settlement event (BS)
  C     City              Build city event (BC)
  R     Road              Build road event (BR)
  LA    Largest army      Largest Army event
  LR    Longest road      Longest Road event

There are 5 types of development cards:

  Type  Name
  -------------------
  KN    Knight
  MO    Monopoly
  RB    Road building
  VP    Victory Point
  YP    Year of plenty

=head2 Events

Events are the things which drive the game: player actions, dice rolls etc. Every entry in CGN is an event, consisting of an event code and a JSON value. Refer to F<example.json> for examples of these events in CGN.

  Code Name                    Value
  ==================================================
  BC   Build city              {"player": "#", "intersection":<intersection coordinates>}
  BD   Build development card  {"player": "#", "type": "KN|MO|RB|VP|YP"}
  BR   Build road              {"player": "#", "path":<path coordinates>}
  BS   Build settlement        {"player": "#", "intersection":<intersection coordinates>}
  CH   Chat                    {"player": "#", "msg": "msg text"}
  CR   Concede resources       {"player": "#", "resources":<resource notation>}
  DR   Dice roll               {"player": "#", "result":#}
  GO   Game Over               {"player": "#"}
  LA   Largest army            {"player": "#", "strength":#}
  LR   Longest road            {"player": "#"}, "length":#}
  MD   Map Define              [ <tile notation> ]
  MO   Monopoly                {"player": "#", "resources":<resource notation>}
  PA   Player Add              {"player": "#"}
  PD   Play development card   {"player": "#", "type": "KN|MO|RB|VP|YP"}
  PE   Phase End               {"phase": "Setup|Deployment|Play|End"}
  PS   Phase Start             {"phase": "Setup|Deployment|Play|End"}
  RA   Robber activate         null
  RD   Robber deactivate       null
  RE   Round End               {"round": #}
  RM   Robber move             {"player": "#", "tile": <tile coordinates>}
  RP   Resource Production     { "resources": <resource notation> }
  RR   Robber rob              { "player":"#", "resources": <resource notation> }
  RS   Round Start             {"round": #}
  TA   Trade accept            {"player": "#", "uuid":"#"}
  TB   Trade bank              {"player": "#", "resources":<resource notation>}
  TC   Trade cancel            {"player": "#", "uuid":"#"}
  TE   Turn End                {"player": "#"}
  TO   Trade offer             {"player": "#", "uuid":"#", "resources":<resource notation>}
  TR   Trade resources         {"player": "#", "uuid":"#", "resources":<resource notation>}
  TS   Turn Start              {"player": "#"}
  YP   Year of plenty          {"player": "#", "resources":<resource notation>}

=head2 Trading

Trading is a big part of Catan. Players may trade with each other or with the Bank. 

Bank trades are described using the trade bank event. For example:

  "TB":{"player":"2", "resources":{"bank":{"B":"-1","O":"4"},"2":{"B":"1","O":"-4"}}

Player trades have two parts: offer and acceptance. A Player may offer a trade to other players with resource notation and a universal unique id (uuid).

The trade offer can be ended with:

=over 4

=item * Trade cancel

The offering player cancels the offer using the trade cancel event.

=item * Trade accept

The other player accepts the trade offer using the trade accept event.

=item * End turn

If a player's turn ends, all outstanding trade offers are cancelled.

=back

Here is an example trade between player 1 and player 2:

  "TO":{"player":"1", "resources":{{"B":-2,"W":1},"2":{"B":2,"W":-1}}, "uuid":"1234-56789-01234"},
  "TA":{"player":"2", "uuid":"1234-56789-01234"},
  "TR":{"resources":{"1":{"B":-2,"W":1},"3":{"B":2,"W":-1}}},

The exchange begins with a Trade offer from player 1 for 1 wool in exchange for 2 brick to player 2. Player 2 accepts the offer, and this triggers the Trade resources event.

=head2 Chat

Player chat uses the event code C<CH>. It provides a key/pair of the player name and the chat text. Here's a conversation:

  "CH": {"player":"1", "msg"::"Let's do this!"},
  "CH": {"player":"2", "msg"::"You're going to lose again"},

Chat is not necessary for game notation, but may help with the implementation of a Catan server using game notation. Server or referee chat messages have the player id C<A> for admin.

=head2 Phases

See the file F<example.json> for an example of CGN notation covering all phases of the game.

=over 4

=item 1 Setup

Setup involves adding players and defining the map.

=item 2 Deployment

Players can deploy settlements and roads in the deployment phase according to the rules of Catan. Player 1 always goes first.

=item 3 Play

This is the regular Catan play action.

=item 4 End

The game is over as a player has won.

=back

=head2 Rounds

A round is one cycle of every player's turn. The Deployment phase has 2 rounds and the Play phase has as many rounds as required to end the game.

=head1 FAQ

=over 4

=item * I<Is CGN case-sensitive?> YES!

=item * I<Why is there no Road Building event?> There is no need for it. When the Play Development card event occurs with a type of C<RB> that indicates road building is active. The player can then build roads using the build road event.

=back

=head2 See Also

L<Catan-Server|https://github.com/dnmfarrell/Catan-Server> is my attempt to implement a Catan game server using CGN.

=head2 Version

0.01

=head2 Author

David Farrell, E<copy> 2015.

=head2 License

FreeBSD, see LICENSE

=cut
